### ISSUE TITLE
week 4 homework

### ISSUE THREAD

**Issue by Excalibur312** [themanoftalent/SignalsSystemsWeek4-7#52]
Teacher, you have merged all your homework to another place, my homework in Week 4 in its place. Can I ask why

**Comment by themanoftalent** [comment]
Certainly, Emre. 
The reason for merging all the homework to another place was due to an issue with the renaming convention. Some of your friends inadvertently added characters like ":" or "\", making the merge process impossible. Therefore, to streamline and ensure the proper organization of everyone's work, the decision was to consolidate all the homework into one central location. The Week 4 homework was included in this process. It is imperative that all pull requests adhere to the proper naming convention. Failure to do so will result in confusion and delays in completing the project. I demand that everyone follow this guideline and, if necessary, request them to re-pull the requests using the correct naming convention.
